/*
    CREACION DE LA TABLA CLIENTE
*/
CREATE TABLE CLIENTE
(
    ID_CLIENTE INT NOT NULL, 
    RUT_CLIENTE VARCHAR2(10) NOT NULL,
    P_NOMBRE_CLIENTE VARCHAR2(30) NOT NULL, --PRIMER NOMBRE
    S_NOMBRE_CLIENTE VARCHAR2(30), --SEGUNDO NOMBRE,OPCIONAL
    APPAT_CLIENTE VARCHAR2(30) NOT NULL, --APELLIDO PATERNO
    APMAT_CLIENTE VARCHAR2(30) NOT NULL, --APELLIDO MATERNO
    TELEFONO_CLIENTE NUMBER(12),
    EMAIL_CLIENTE VARCHAR2(50) NOT NULL
)

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE);

/*
    CREACION DE LA TABLA DEPARTAMENTO
*/
CREATE TABLE DEPARTAMENTO
(
ID_DEPARTAMENTO INT NOT NULL,
NOMBCIUDAD_DEPARTAMENTO VARCHAR2(50) NOT NULL, --NOMBRE DE LA CIUDAD EN LA QUE SE UBICA EL DEPARTAMENTO
DIRECION_DEPARTAMENTO VARCHAR2 (50) NOT NULL,
CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(ID_DEPARTAMENTO) --, 
--FOTOGRAFIA BLOB
)

/*
    CREACION DE LA TABLA CRUZADA CLIENTE_DEPARTAMENTO
*/

CREATE TABLE CLIENTE_DEPARTAMENTO
(
ID_CLIENTE_CLIENTE INT NOT NULL,
ID_DEPARTAMENTO_DEPARTAMENTO INT NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY(ID_CLIENTE_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO_DEPARTAMENTO)REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
)

/*
    CREAMOS LA TABLA EMPLEADO
*/

CREATE TABLE EMPLEADO 
(
    IDEMPLEADO NUMBER(10) NOT NULL,
    NOMBRES VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    CEDULA VARCHAR2(10) NOT NULL,
    ESTADO_CIVIL VARCHAR2(1) NOT NULL,
    GENERO VARCHAR2(1) NOT NULL,
    EDAD NUMBER(3) NOT NULL
)

ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY(IDEMPLEADO);

INSERT INTO EMPLEADO (IDEMPLEADO, NOMBRES, APELLIDOS, CEDULA, ESTADO_CIVIL, GENERO, EDAD) VALUES (1, 'AAAAA', 'AAAAA', 'AAA', 'S', 'M', 23 );
                
                
-- CREAMOS LA TABLA LOGIN
CREATE TABLE LOGIN
(
ID INT  NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
CONTRASENA VARCHAR(50) NOT NULL,
PRIVILEGIO VARCHAR2(50),
ACTIVO INT
)




-- ASIGNAMOS ID COMO PRIMARY KEY DE LA TABLA LOGIN CON EL NOMBRE PK_LOGIN
ALTER TABLE LOGIN ADD CONSTRAINT PK_LOGIN PRIMARY KEY(ID);

-- CREAMOS SECUENCIA LOGIN_SEQ
CREATE SEQUENCE LOGIN_SEQ
                START WITH 1
                INCREMENT BY 1;
                
-- INSERTAMOS VARIOS USUARIOS PARA PROBAR
INSERT INTO LOGIN VALUES (LOGIN_SEQ.NEXTVAL, 'Keiro', 'keiropalomera', 'Cliente', 1);
INSERT INTO LOGIN VALUES (LOGIN_SEQ.NEXTVAL, 'Carlos', '12345', 'Administrador', 1);
INSERT INTO LOGIN VALUES (LOGIN_SEQ.NEXTVAL, 'Daniel', '20201', 'Cliente', 1);
INSERT INTO LOGIN VALUES (LOGIN_SEQ.NEXTVAL, 'German', '98765', 'Administrador', 1);

select * from cliente;