/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaVistasClientes;

import capaVistas.VLogin;
import capaEntidades.Cliente;
import capaNegocios.NegCliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Keiro
 */
public class VCliModifcar extends javax.swing.JFrame {

    /**
     * Creates new form VCliModifcar
     */
    
    private NegCliente nCli = new NegCliente();
   
    
    public VCliModifcar() {
        initComponents();
        
        btnLimpiar.setEnabled(false);
        setTitle("MODIFICAR");
        setLocationRelativeTo(null);
        setResizable(false);
        
        nCli.listarCliente(tbClientesM);
    }
    
    private void habilitarBotonLimpiar(){
        if(txtIdM.getText().isEmpty() && txtRutM.getText().isEmpty() && txtPrNombM.getText().isEmpty()
           && txtSNombM.getText().isEmpty() && txtApPatM.getText().isEmpty() && txtApMatM.getText().isEmpty()
           && txtTelefonoM.getText().isEmpty()
           && txtEmailM.getText().isEmpty()){
        btnLimpiar.setEnabled(false);
    } else{
            btnLimpiar.setEnabled(true);
        }
    }
   
    
    public void limpiar(){
        txtIdM.setText("");
        txtRutM.setText("");
        txtPrNombM.setText("");
        txtSNombM.setText("");
        txtApPatM.setText("");
        txtApMatM.setText("");
        txtTelefonoM.setText("");
        txtEmailM.setText("");
        habilitarBotonLimpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdM = new javax.swing.JTextField();
        txtRutM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrNombM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApMatM = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefonoM = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientesM = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtEmailM = new javax.swing.JTextField();
        txtSNombM = new javax.swing.JTextField();
        txtApPatM = new javax.swing.JTextField();
        jBMCli = new javax.swing.JMenuBar();
        jMOpcionesM = new javax.swing.JMenu();
        jMIVAtras1 = new javax.swing.JMenuItem();
        jMICSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MODIFICAR CLIENTES");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Primer Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Segundo Nombre:");

        txtIdM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMActionPerformed(evt);
            }
        });
        txtIdM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdMKeyReleased(evt);
            }
        });

        txtRutM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutMKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Rut");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ID:");

        txtPrNombM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrNombMKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Apellido Paterno:");

        txtApMatM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApMatMKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Apellido Materno:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Telefono:");

        txtTelefonoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoMKeyReleased(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tbClientesM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbClientesM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientesM);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Email:");

        txtEmailM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailMKeyReleased(evt);
            }
        });

        txtSNombM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSNombMKeyReleased(evt);
            }
        });

        txtApPatM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApPatMKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtApMatM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)
                                .addComponent(txtApPatM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(156, 156, 156)
                                .addComponent(txtRutM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmailM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrNombM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSNombM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtIdM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtRutM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtPrNombM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSNombM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtApPatM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtApMatM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTelefonoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtEmailM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnLimpiar)
                            .addComponent(btnSalir))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMOpcionesM.setText("Opciones");

        jMIVAtras1.setText("Volver atras");
        jMIVAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVAtras1ActionPerformed(evt);
            }
        });
        jMOpcionesM.add(jMIVAtras1);

        jMICSesion.setText("Cerrar Sesion");
        jMICSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICSesionActionPerformed(evt);
            }
        });
        jMOpcionesM.add(jMICSesion);

        jBMCli.add(jMOpcionesM);

        setJMenuBar(jBMCli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (txtIdM.getText().isEmpty() || txtRutM.getText().isEmpty() ||
            txtPrNombM.getText().isEmpty() || txtApPatM.getText().isEmpty()||
            txtApMatM.getText().isEmpty() || txtTelefonoM.getText().isEmpty() ||
            txtEmailM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos,  (Segundo nombre es opcional)");
        }
        else {
            Cliente cli = new Cliente();
            cli.setIDCliente(Integer.parseInt(txtIdM.getText()));
            cli.setRutCliente(txtRutM.getText());
            cli.setpNombreCliente(txtPrNombM.getText());
            cli.setsNombreCliente(txtSNombM.getText());
            cli.setApPatCliente(txtApPatM.getText());
            cli.setApMatCliente(txtApMatM.getText());
            cli.setTelefonoCliente(Integer.parseInt(txtTelefonoM.getText()));
            cli.setEmailCliente(txtEmailM.getText());
            String mensaje = nCli.modificarCliente(cli);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            nCli.listarCliente(tbClientesM);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tbClientesMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMMouseClicked
        int seleccion = tbClientesM.rowAtPoint(evt.getPoint());
        txtIdM.setText(tbClientesM.getValueAt(seleccion, 0)+"");
        txtRutM.setText(tbClientesM.getValueAt(seleccion, 1)+"");
        txtPrNombM.setText(tbClientesM.getValueAt(seleccion, 2)+"");
        txtSNombM.setText(tbClientesM.getValueAt(seleccion, 3)+"");
        txtApPatM.setText(tbClientesM.getValueAt(seleccion, 4)+"");
        txtApMatM.setText(tbClientesM.getValueAt(seleccion, 5)+"");
        txtTelefonoM.setText(tbClientesM.getValueAt(seleccion, 6)+"");
        txtEmailM.setText(tbClientesM.getValueAt(seleccion, 7)+"");
    }//GEN-LAST:event_tbClientesMMouseClicked

    private void jMICSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICSesionActionPerformed
        VLogin vLog = new VLogin();
        vLog.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMICSesionActionPerformed

    private void jMIVAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVAtras1ActionPerformed
        VAdminClientes vAC = new VAdminClientes();
        vAC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMIVAtras1ActionPerformed

    private void txtIdMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMKeyReleased
        habilitarBotonLimpiar();
    }//GEN-LAST:event_txtIdMKeyReleased

    private void txtRutMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutMKeyReleased
        habilitarBotonLimpiar();       
    }//GEN-LAST:event_txtRutMKeyReleased

    private void txtPrNombMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrNombMKeyReleased
        habilitarBotonLimpiar();
    }//GEN-LAST:event_txtPrNombMKeyReleased

    private void txtSNombMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSNombMKeyReleased
        habilitarBotonLimpiar();
    }//GEN-LAST:event_txtSNombMKeyReleased

    private void txtApPatMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApPatMKeyReleased
        habilitarBotonLimpiar();
    }//GEN-LAST:event_txtApPatMKeyReleased

    private void txtApMatMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApMatMKeyReleased
        habilitarBotonLimpiar();
    }//GEN-LAST:event_txtApMatMKeyReleased

    private void txtTelefonoMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoMKeyReleased
        habilitarBotonLimpiar();
    }//GEN-LAST:event_txtTelefonoMKeyReleased

    private void txtEmailMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailMKeyReleased
        habilitarBotonLimpiar();
    }//GEN-LAST:event_txtEmailMKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliModifcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliModifcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliModifcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliModifcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliModifcar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuBar jBMCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMICSesion;
    private javax.swing.JMenuItem jMIVAtras1;
    private javax.swing.JMenu jMOpcionesM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientesM;
    private javax.swing.JTextField txtApMatM;
    private javax.swing.JTextField txtApPatM;
    private javax.swing.JTextField txtEmailM;
    private javax.swing.JTextField txtIdM;
    private javax.swing.JTextField txtPrNombM;
    private javax.swing.JTextField txtRutM;
    private javax.swing.JTextField txtSNombM;
    private javax.swing.JTextField txtTelefonoM;
    // End of variables declaration//GEN-END:variables
}
