/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaVistasClientes;

import capaVistas.VLogin;
import capaDb.Conexion;
import capaNegocios.NegCliente;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Keiro
 */
public class VCliBuscar extends javax.swing.JFrame {
    
    private VCliAgregar vCliA = new VCliAgregar();
    private NegCliente nCli = new NegCliente();

    /**
     * Creates new form VEmpEliminar
     */
    public VCliBuscar() {
        initComponents();
        nCli.listarCliente(tbClientesB);
        llenarCbB();
        btnBuscar.setEnabled(false);
        
        
        setTitle("BUSCAR CLIENTES");
        setLocationRelativeTo(null);
        setResizable(false);
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtOpcionB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientesB = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        cBOpciones = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMOpcionesE = new javax.swing.JMenu();
        jMILTabla = new javax.swing.JMenuItem();
        jMIVAE = new javax.swing.JMenuItem();
        jMICSE = new javax.swing.JMenuItem();
        jMISalirE = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtOpcionB.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtOpcionB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOpcionBKeyReleased(evt);
            }
        });

        tbClientesB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbClientesB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientesB);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BUSCAR CLIENTES");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Buscar por:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cBOpciones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cBOpciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cBOpcionesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(276, 276, 276))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cBOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscar)
                    .addComponent(cBOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMOpcionesE.setText("Opciones");

        jMILTabla.setText("Llenar Tabla");
        jMILTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILTablaActionPerformed(evt);
            }
        });
        jMOpcionesE.add(jMILTabla);

        jMIVAE.setText("Volver atras");
        jMIVAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVAEActionPerformed(evt);
            }
        });
        jMOpcionesE.add(jMIVAE);

        jMICSE.setText("Cerrar Sesion");
        jMICSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICSEActionPerformed(evt);
            }
        });
        jMOpcionesE.add(jMICSE);

        jMISalirE.setText("Salir");
        jMISalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirEActionPerformed(evt);
            }
        });
        jMOpcionesE.add(jMISalirE);

        jMenuBar1.add(jMOpcionesE);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbClientesBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesBMouseClicked
//        int seleccion = tbClientesB.rowAtPoint(evt.getPoint());
//        txtOpcionB.setText(tbClientesB.getValueAt(seleccion, 0)+"");
    }//GEN-LAST:event_tbClientesBMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String opciones = (String) cBOpciones.getSelectedItem();
        
        if (txtOpcionB.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar un id");
        } 
        else{
            try {
                DefaultTableModel modelo=new DefaultTableModel();
                tbClientesB.setModel(modelo);
                PreparedStatement ps= null;
                ResultSet rs=null;
                Connection con = Conexion.getConnection();
                String sql = "";
                
                switch(opciones){
                    case "Id":
                        sql="SELECT ID_CLIENTE, RUT_CLIENTE, P_NOMBRE_CLIENTE, S_NOMBRE_CLIENTE, "
                          + "APPAT_CLIENTE, APMAT_CLIENTE ,TELEFONO_CLIENTE, EMAIL_CLIENTE  "
                          + "FROM CLIENTE WHERE ID_CLIENTE='"+txtOpcionB.getText()+"'";
                        break;
                    case "Rut":
                        sql="SELECT ID_CLIENTE, RUT_CLIENTE, P_NOMBRE_CLIENTE, S_NOMBRE_CLIENTE, "
                          + "APPAT_CLIENTE, APMAT_CLIENTE ,TELEFONO_CLIENTE, EMAIL_CLIENTE  "
                          + "FROM CLIENTE WHERE RUT_CLIENTE='"+txtOpcionB.getText()+"'";
                        break;
                    case "Primer Nombre":
                        sql="SELECT ID_CLIENTE, RUT_CLIENTE, P_NOMBRE_CLIENTE, S_NOMBRE_CLIENTE, "
                          + "APPAT_CLIENTE, APMAT_CLIENTE ,TELEFONO_CLIENTE, EMAIL_CLIENTE  "
                          + "FROM CLIENTE WHERE P_NOMBRE_CLIENTE='"+txtOpcionB.getText()+"'";
                        break;
                    case "Apellido Paterno":
                        sql="SELECT ID_CLIENTE, RUT_CLIENTE, P_NOMBRE_CLIENTE, S_NOMBRE_CLIENTE, "
                          + "APPAT_CLIENTE, APMAT_CLIENTE ,TELEFONO_CLIENTE, EMAIL_CLIENTE  "
                          + "FROM CLIENTE WHERE APPAT_CLIENTE='"+txtOpcionB.getText()+"'";
                        break;
                    case "Telefono":
                        sql="SELECT ID_CLIENTE, RUT_CLIENTE, P_NOMBRE_CLIENTE, S_NOMBRE_CLIENTE, "
                          + "APPAT_CLIENTE, APMAT_CLIENTE ,TELEFONO_CLIENTE, EMAIL_CLIENTE  "
                          + "FROM CLIENTE WHERE TELEFONO_CLIENTE='"+txtOpcionB.getText()+"'";
                        break;
                    case "E-mail":
                        sql="SELECT ID_CLIENTE, RUT_CLIENTE, P_NOMBRE_CLIENTE, S_NOMBRE_CLIENTE, "
                          + "APPAT_CLIENTE, APMAT_CLIENTE ,TELEFONO_CLIENTE, EMAIL_CLIENTE  "
                          + "FROM CLIENTE WHERE EMAIL_CLIENTE='"+txtOpcionB.getText()+"'";
                        break;
                        default:
                            JOptionPane.showMessageDialog(null, "Debe seleccionar una opcion valida");
                            break;
                }
                
                ps= con.prepareStatement(sql);
                rs=ps.executeQuery();
                ResultSetMetaData rsMd= rs.getMetaData();
                int cantidadColumnas = rsMd.getColumnCount();
            
                modelo.addColumn("ID");
                modelo.addColumn("RUT CLIENTE");
                modelo.addColumn("PRIMER NOMBRE");
                modelo.addColumn("SEGUNDO NOMBRE");
                modelo.addColumn("APELLIDO PATERNO");
                modelo.addColumn("APELLIDO MATERNO");
                modelo.addColumn("TELEFONO");
                modelo.addColumn("EMAIL");
                
                while(rs.next()){
                
                    Object[] filas =new Object[cantidadColumnas];
                
                    for (int i = 0; i < cantidadColumnas; i++) 
                    {
                        filas[i] =rs.getObject(i+1);
                    }
                
                    modelo.addRow(filas);
                }   
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }          
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    
    private void jMISalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirEActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMISalirEActionPerformed

    private void jMICSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICSEActionPerformed
        VLogin vLog= new VLogin();
        vLog.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMICSEActionPerformed

    private void jMIVAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVAEActionPerformed
        VAdminClientes vAC= new VAdminClientes();
        vAC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMIVAEActionPerformed

    private void cBOpcionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cBOpcionesItemStateChanged
        
    }//GEN-LAST:event_cBOpcionesItemStateChanged

    private void jMILTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILTablaActionPerformed
        nCli.listarCliente(tbClientesB);
    }//GEN-LAST:event_jMILTablaActionPerformed

    private void txtOpcionBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOpcionBKeyReleased
        habilitarBtnBuscar();
    }//GEN-LAST:event_txtOpcionBKeyReleased

    //Llenar combobox con un metodo
    public void llenarCbB(){
        cBOpciones.addItem("Id");
        cBOpciones.addItem("Rut");
        cBOpciones.addItem("Primer Nombre");
        cBOpciones.addItem("Apellido Paterno");
        cBOpciones.addItem("Telefono");
        cBOpciones.addItem("E-mail");
    }
    
    public void habilitarBtnBuscar(){
        if(txtOpcionB.getText().isEmpty()){
            btnBuscar.setEnabled(false);
        }
        else{
            btnBuscar.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliBuscar().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cBOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMICSE;
    private javax.swing.JMenuItem jMILTabla;
    private javax.swing.JMenuItem jMISalirE;
    private javax.swing.JMenuItem jMIVAE;
    private javax.swing.JMenu jMOpcionesE;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientesB;
    private javax.swing.JTextField txtOpcionB;
    // End of variables declaration//GEN-END:variables
}
