/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaVistasDepartamentos;

import capaVistasDepartamentos.*;
import capaVistas.VLogin;
import capaEntidades.Departamento;
import capaNegocios.NegDepartamento;
import javax.swing.JOptionPane;

/**
 *
 * @author Keiro
 */
public class VDptoModifcar extends javax.swing.JFrame {

    /**
     * Creates new form VDptoModifcar
     */
    
    private NegDepartamento nDpto = new NegDepartamento();
   
    
    public VDptoModifcar() {
        initComponents();
        
        jMILimpiarM.setEnabled(false);
        setTitle("MODIFICAR");
        setLocationRelativeTo(null);
        setResizable(false);
        
        nDpto.listarDepartamento(tbDptoM);
    }
    
    private void habilitarBotonLimpiar(){
        if(txtIdM.getText().isEmpty() && txtNombCDptoM.getText().isEmpty() 
        && txtDireccionDptoM.getText().isEmpty()){
        jMILimpiarM.setEnabled(false);
    } else{
            jMILimpiarM.setEnabled(true);
        }
    }
   
    
    public void limpiar(){
        txtIdM.setText("");
        txtNombCDptoM.setText("");
        txtDireccionDptoM.setText("");
        habilitarBotonLimpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdM = new javax.swing.JTextField();
        txtNombCDptoM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDireccionDptoM = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDptoM = new javax.swing.JTable();
        jBMCli = new javax.swing.JMenuBar();
        jMOpcionesM = new javax.swing.JMenu();
        jMILimpiarM = new javax.swing.JMenuItem();
        jMIVAtras1 = new javax.swing.JMenuItem();
        jMICSesion = new javax.swing.JMenuItem();
        jMISalirM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MODIFICAR DEPARTAMENTOS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Direccion:");

        txtIdM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMActionPerformed(evt);
            }
        });
        txtIdM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdMKeyReleased(evt);
            }
        });

        txtNombCDptoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombCDptoMKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nombre Ciudad:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ID:");

        txtDireccionDptoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionDptoMKeyReleased(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        tbDptoM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbDptoM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDptoMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDptoM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDireccionDptoM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombCDptoM, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombCDptoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccionDptoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jMOpcionesM.setText("Opciones");

        jMILimpiarM.setText("Limpiar");
        jMILimpiarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILimpiarMActionPerformed(evt);
            }
        });
        jMOpcionesM.add(jMILimpiarM);

        jMIVAtras1.setText("Volver atras");
        jMIVAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVAtras1ActionPerformed(evt);
            }
        });
        jMOpcionesM.add(jMIVAtras1);

        jMICSesion.setText("Cerrar Sesion");
        jMICSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICSesionActionPerformed(evt);
            }
        });
        jMOpcionesM.add(jMICSesion);

        jMISalirM.setText("Salir");
        jMISalirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirMActionPerformed(evt);
            }
        });
        jMOpcionesM.add(jMISalirM);

        jBMCli.add(jMOpcionesM);

        setJMenuBar(jBMCli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (txtIdM.getText().isEmpty() || txtNombCDptoM.getText().isEmpty() ||
            txtDireccionDptoM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos,  (Segundo nombre es opcional)");
        }
        else {
            Departamento dpto = new Departamento();
            dpto.setIDDepartamento(Integer.parseInt(txtIdM.getText()));
            dpto.setNombCiudadDepartamento(txtNombCDptoM.getText());
            dpto.setDireccionDepartamento(txtDireccionDptoM.getText());
            String mensaje = nDpto.modificarDepartamento(dpto);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            nDpto.listarDepartamento(tbDptoM);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tbDptoMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDptoMMouseClicked
        int seleccion = tbDptoM.rowAtPoint(evt.getPoint());
        txtIdM.setText(tbDptoM.getValueAt(seleccion, 0)+"");
        txtNombCDptoM.setText(tbDptoM.getValueAt(seleccion, 1)+"");
        txtDireccionDptoM.setText(tbDptoM.getValueAt(seleccion, 2)+"");
    }//GEN-LAST:event_tbDptoMMouseClicked

    private void jMICSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICSesionActionPerformed
        VLogin vLog = new VLogin();
        vLog.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMICSesionActionPerformed

    private void jMIVAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVAtras1ActionPerformed
        VAdminDpto vADpto = new VAdminDpto();
        vADpto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMIVAtras1ActionPerformed

    private void txtIdMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMKeyReleased
        habilitarBotonLimpiar();
    }//GEN-LAST:event_txtIdMKeyReleased

    private void txtNombCDptoMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombCDptoMKeyReleased
        habilitarBotonLimpiar();       
    }//GEN-LAST:event_txtNombCDptoMKeyReleased

    private void txtDireccionDptoMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionDptoMKeyReleased
        habilitarBotonLimpiar();
    }//GEN-LAST:event_txtDireccionDptoMKeyReleased

    private void jMILimpiarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILimpiarMActionPerformed
        limpiar();
    }//GEN-LAST:event_jMILimpiarMActionPerformed

    private void jMISalirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirMActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jMISalirMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VDptoModifcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VDptoModifcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VDptoModifcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VDptoModifcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VDptoModifcar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JMenuBar jBMCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMICSesion;
    private javax.swing.JMenuItem jMILimpiarM;
    private javax.swing.JMenuItem jMISalirM;
    private javax.swing.JMenuItem jMIVAtras1;
    private javax.swing.JMenu jMOpcionesM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDptoM;
    private javax.swing.JTextField txtDireccionDptoM;
    private javax.swing.JTextField txtIdM;
    private javax.swing.JTextField txtNombCDptoM;
    // End of variables declaration//GEN-END:variables
}
